# Generated by Django 3.2.16 on 2023-11-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20231108_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagInRecipe',
        ),
    ]
