# Generated by Django 3.2.16 on 2023-11-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20231108_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagInRecipe',
        ),
    ]
